before_script:
  - pip install -r requirements.txt

stages:
  - build
  - upload

variables:
  PROTO_FILE_URL: https://raw.githubusercontent.com/zeebe-io/zeebe/0.21.1/gateway-protocol/src/main/proto/gateway.proto
  PROTO_FILE_PATH: zeebe_grpc
  PROTO_FILE_NAME: gateway.proto

build:
  stage: build
  script:
    - wget -O $PROTO_FILE_PATH/$PROTO_FILE_NAME $PROTO_FILE_URL
    - python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. $PROTO_FILE_PATH/$PROTO_FILE_NAME
    - python setup.py sdist bdist_wheel

upload:
  stage: upload
    - twine upload dist/*
