before_script:
  - pip install -r requirements.txt

stages:
  - build
  - deploy

build_latest:
  stage: build
  only:
    - master
  script:
    - echo $PYPI_USER

deploy_latest:
  stage: deploy
  only:
    - master
  script:
    - echo $PYPI_USER