before_script:
  - docker info

stages:
  - build
  - deploy

build_latest:
  stage: build
  only:
    - master
  script:
    -
    - echo $PYPI_USER

deploy_latest:
  stage: deploy
  only:
    - master
  script:
    - echo $PYPI_USER

