before_script:
  - pip install -r requirements.txt

stages:
  - build
  - deploy

variables:
  PROTO_FILE: https://raw.githubusercontent.com/zeebe-io/zeebe/0.20.0/gateway-protocol/src/main/proto/gateway.proto

build_latest:
  stage: build
  only:
    - master
  script:
    - cd zeebe_grpc
    - wget $PROTO_FILE
    - python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. gateway.proto

deploy_latest:
  stage: deploy
  only:
    - master
  script:
    - echo $PYPI_USER