name: Build gRPC

on:
  release:
    types: [published]
    
permissions:
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Download proto file
      run: wget -O src/zeebe_grpc/gateway.proto https://raw.githubusercontent.com/camunda-cloud/zeebe/8.0.5/gateway-protocol/src/main/proto/gateway.proto
    - name: Build gRPC stubs
      run: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. src/zeebe_grpc/gateway.proto
    - name: Build package
      run: python -m build
